name: todo_app
description: Todop.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  meta: ^1.7.0
  animated_bottom_navigation_bar: ^1.1.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  sqflite: ^2.0.3+1
  flutter_bloc: ^8.1.1
  flutter_slidable: ^2.0.0
  table_calendar: ^3.0.7
  percent_indicator: ^4.2.2
  flutter_native_splash: ^2.2.14

flutter_native_splash:
  color: "#FFFFFF"
  # background_image: lib/assets/images/ic_appIcon.png
  image: lib/assets/images/todo-icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
